[msbuild]
project = "YT2MP3Sharp.sln"
configuration = "Release"
version = "0.1.0"
output = "bin/Release/net8.0/YT2MP3Sharp.zip"
runtime = "win-x64"

[github]
user = "VLDG2712"
repo = "YT2MP3Sharp-Avalonia"
version_prefix = "v"

[msbuild.properties]
PublishReadyToRun = true
