name: myworkflow
on:
  push:
    tags:
      - 'v*'
jobs:
    build:
        name: Publish Binaries
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
               dotnet-version: 8.0.x
            - name: Restore dependencies
              run: dotnet restore
            - name: Build
              run: dotnet build --no-restore
            - name: Publish
              run: dotnet publish -c Release -o ./bin
            - name: Archive
              uses: edgarrc/action-7z@v1
              with:
               args: 7z a -tzip -mx=9 build.zip ./bin/
            - name: Upload
              uses: actions/upload-release-action@v2
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: publish.zip
                name: publish
                asset_name: YT2MP3Sharp.zip
                tag: ${{ github.ref }}
                overwrite: true
                body: "This is a test"